/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface IconButtonProps {
  src: string;
  alt: string;
  className?: string;
  onClick?: () => void;
}

const IconButton: React.FC<IconButtonProps> = ({
  src,
  alt,
  className = "",
  onClick,
}) => (
  <div
    className={`flex flex-col justify-center items-center p-3 rounded ${className}`}
    onClick={onClick}
    role="button"
    tabIndex={0}
    onKeyPress={(e) => e.key === "Enter" && onClick && onClick()}
  >
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain w-4 aspect-square"
    />
  </div>
);

export default IconButton;
