/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const EmailSignIn: React.FC = () => {
  return (
    <form>
      <label htmlFor="email" className="sr-only">
        Enter your email
      </label>
      <input
        id="email"
        type="email"
        className="flex overflow-hidden flex-col justify-center px-3.5 py-3 text-white rounded-md border border-solid backdrop-blur-[20px] bg-white bg-opacity-10 border-white border-opacity-10 max-w-[280px] min-h-[40px] w-full"
        placeholder="Enter your email"
      />
      <button type="submit" className="flex flex-col pt-4 w-full text-white">
        <span className="self-stretch px-20 py-2.5 max-w-full rounded-3xl opacity-40 backdrop-blur-[10px] bg-white bg-opacity-10 min-h-[40px] w-[280px] max-md:px-5">
          Sign in with email
        </span>
      </button>
    </form>
  );
};

export default EmailSignIn;
