/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SignInButtonProps {
  provider: string;
  icon: string;
}

const SignInButton: React.FC<SignInButtonProps> = ({ provider, icon }) => {
  return (
    <button className="flex gap-1.5 justify-center items-center px-16 py-2.5 mt-4 max-w-full rounded-3xl backdrop-blur-[10px] bg-white bg-opacity-10 min-h-[40px] w-[280px] max-md:px-5">
      <img
        loading="lazy"
        src={icon}
        alt={`${provider} icon`}
        className="object-contain shrink-0 self-stretch my-auto aspect-square w-[17px]"
      />
      <span className="self-stretch my-auto">Sign in with {provider}</span>
    </button>
  );
};

export default SignInButton;
