/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface FeatureItemProps {
  title: string;
  description: string;
  imageSrc: string;
}

const FeatureItem: React.FC<FeatureItemProps> = ({
  title,
  description,
  imageSrc,
}) => {
  return (
    <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col pr-px pb-7 pl-6 mx-auto w-full tracking-tight rounded-xl bg-neutral-900 text-neutral-400 max-md:pl-5 max-md:mt-6">
        <img
          loading="lazy"
          src={imageSrc}
          className="object-contain ml-2.5 w-full aspect-[1.28]"
          alt={title}
        />
        <h3 className="self-start mt-8 text-lg font-semibold tracking-tight text-zinc-100">
          {title}
        </h3>
        <p className="mt-1.5 mr-7 text-sm leading-5 max-md:mr-2.5">
          {description}
        </p>
      </div>
    </div>
  );
};

const features = [
  {
    title: 'A type-safe SDK',
    description:
      "Install and run our SDK generator, which introspects your repositories' content to output automatic TypeScript types.",
    imageSrc:
      'https://cdn.builder.io/api/v1/image/assets/TEMP/8b355614aff67d0189c0c47bd31aa99522f97867336611052a618247ff44c32d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197',
  },
  {
    title: 'All the essentials, and then some',
    description:
      'Choose from a wide selection of blocks. Use primitive blocks—text, images, dates, etc—, or more complex ones —collections, components, and more.',
    imageSrc:
      'https://cdn.builder.io/api/v1/image/assets/TEMP/03d550f8fb4058cef17c68ed2ca7e4d37693c8b5e626c4059a3ab2551965d13b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197',
  },
  {
    title: 'A Diff View to see your changes',
    description:
      "See what you're about to commit across your whole repository with the diff view. Discard changes if you've made a mistake.",
    imageSrc:
      'https://cdn.builder.io/api/v1/image/assets/TEMP/7b3fd45f23fcd76c36bbaa5222502270332710a8876253b8a5a5ea9335aa8086?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197',
  },
];

const AdditionalFeatures: React.FC = () => {
  return (
    <section className="mt-6 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        {features.map((feature, index) => (
          <FeatureItem key={index} {...feature} />
        ))}
      </div>
    </section>
  );
};

export default AdditionalFeatures;
