/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const BlogIntro: React.FC = () => {
  return (
    <div className="flex flex-col max-w-full text-sm tracking-tight leading-loose rounded-full text-stone-500 w-[300px]">
      <div className="flex flex-col justify-center p-px">
        <div className="px-3 py-2 rounded-full">
          From the Blog — Introducing BaseHub Templates
        </div>
      </div>
    </div>
  );
};

export default BlogIntro;
