/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const CTABanner: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col justify-center p-px mt-6 w-full font-medium rounded-xl max-md:max-w-full">
      <div className="flex overflow-hidden relative flex-col flex-wrap gap-5 justify-between px-6 py-6 w-full min-h-[82px] max-md:px-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/53c2bd2357c8398c9e1758c5fcf1f122506b65919f5285fbba8e94fd91c10cad?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
          className="object-cover absolute inset-0 size-full"
          alt="Background"
        />
        <h2 className="relative my-auto text-2xl tracking-tighter leading-loose text-black">
          Try BaseHub Today
        </h2>
        <a
          href="#get-started"
          className="overflow-hidden relative px-3.5 py-3 text-sm tracking-tight leading-none text-center bg-zinc-900 rounded-[96px] text-stone-300"
        >
          Get Started
        </a>
      </div>
    </div>
  );
};

export default CTABanner;
