/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const CTASection: React.FC = () => {
  return (
    <section className="flex flex-col self-center py-px w-full max-w-[1441px] rounded-[60px_60px_0px_0px] max-md:max-w-full">
      <div className="flex overflow-hidden relative flex-col justify-center items-center px-16 py-16 w-full min-h-[179px] rounded-[58px_58px_0px_0px] max-md:px-5 max-md:mr-0.5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/7b4602c2e9ba25ed1f19169da637ece4868475e3299b470e005bb1b98f738ddb?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
          className="object-cover absolute inset-0 size-full"
          alt="Background"
        />
        <div className="flex relative flex-wrap gap-5 justify-between max-w-full w-[1197px]">
          <div className="flex flex-col">
            <h2 className="self-start text-2xl font-medium tracking-tighter leading-none text-zinc-100">
              Try BaseHub Today
            </h2>
            <p className="mt-4 text-base tracking-tight leading-loose text-neutral-400">
              Start for free, then grow with your team.
            </p>
          </div>
          <a
            href="#get-started"
            className="overflow-hidden px-3.5 py-3 my-auto text-sm font-medium tracking-tight leading-none text-center text-white bg-orange-500 rounded-[96px]"
          >
            Get Started
          </a>
        </div>
      </div>
    </section>
  );
};

export default CTASection;
