/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface FAQItemProps {
  question: string;
  iconSrc: string;
}
const FAQItem: React.FC<FAQItemProps> = ({ question, iconSrc }) => {
  return (
    <div className="flex flex-wrap gap-2 px-3.5 py-4 mt-3 text-sm tracking-tight leading-loose bg-black rounded-lg text-zinc-100">
      <img
        loading="lazy"
        src={iconSrc}
        className="object-contain shrink-0 aspect-square w-[18px]"
        alt=""
      />
      <div className="flex-auto my-auto max-md:max-w-full">{question}</div>
    </div>
  );
};

export default FAQItem;
