/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface FeatureProps {
  title: string;
  description: string;
  imageSrc: string;
}

const Feature: React.FC<FeatureProps> = ({ title, description, imageSrc }) => {
  return (
    <div className="flex flex-col items-start px-6 py-6 w-full rounded-xl bg-neutral-900 max-md:px-5">
      <h3 className="text-lg font-semibold tracking-tight text-zinc-100">
        {title}
      </h3>
      <p className="mt-6 text-sm tracking-tight leading-5 text-neutral-400 max-md:mr-2.5">
        {description}
      </p>
      <img
        loading="lazy"
        src={imageSrc}
        className="object-contain grow w-full aspect-[1.13] max-md:mt-10"
        alt={title}
      />
    </div>
  );
};

export default Feature;
