/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Feature from './Feature';

const features = [
  {
    title: 'Realtime, Multiplayer Presence',
    description:
      "Work with your team in real time. You'll see their faces as they move through the Repository.",
    imageSrc:
      'https://cdn.builder.io/api/v1/image/assets/TEMP/d78d59d0863112f3201b60d241e264abcda48c3315c34e280274d082531c5628?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197',
  },
  {
    title: 'AI Structure Generation',
    description:
      'Generate entire content models with natural language. Try it out with things like "a blog post about space travel", or "model a documentation site".',
    imageSrc:
      'https://cdn.builder.io/api/v1/image/assets/TEMP/0a02c388a64af5f1b8bd461e813e19f6594743c76c02f55795d214fac2fa0f71?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197',
  },
];

const FeatureSection: React.FC = () => {
  return (
    <section className="flex flex-col self-start mt-11 ml-12 max-w-full w-[1236px] max-md:mt-10">
      <div className="w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {features.map((feature, index) => (
            <div
              key={index}
              className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
            >
              <Feature {...feature} />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeatureSection;
