/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col items-center px-20 pb-12 mt-12 bg-black max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex z-10 flex-col max-w-full w-[1197px]">
        <div className="flex flex-wrap gap-5 justify-between text-sm tracking-tight text-center text-zinc-100 max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/62a829901c59abacbe074a2ac71d08542dc83e65730316ba6c4a8c24fdc2749a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
            className="object-contain shrink-0 aspect-[0.74] w-[59px]"
            alt="BaseHub Logo"
          />
          <nav className="flex flex-col my-auto">
            <div className="flex gap-5 justify-between self-end leading-none whitespace-nowrap">
              <a href="#home">Home</a>
              <a href="#changelog">Changelog</a>
              <a href="#docs">Docs</a>
            </div>
            <div className="flex gap-5 mt-5">
              <a href="#terms" className="flex-auto leading-none">
                Terms of Service
              </a>
              <a href="#privacy" className="leading-none">
                Privacy Policy
              </a>
            </div>
          </nav>
        </div>
        <div className="flex flex-wrap gap-5 justify-between mt-11 w-full max-md:mt-10 max-md:max-w-full">
          <p className="self-start mt-4 text-sm tracking-tight leading-loose text-center text-neutral-400 max-md:max-w-full">
            © 2024 BaseHub – Fast, Collaborative, AI-Native Content Management.
          </p>
          <div className="flex">
            <a href="#twitter" aria-label="Twitter">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/0a422b90555ac2645f0fe88160152541328ee3a6cfb35829081d11a147b22a69?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                className="object-contain shrink-0 rounded aspect-[1.47] w-[47px]"
                alt="Twitter"
              />
            </a>
            <a href="#github" aria-label="GitHub">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/047c22c155e170917b38bc88e0f9668a576e30e951e184684983df3200044808?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                className="object-contain shrink-0 rounded aspect-[1.47] w-[47px]"
                alt="GitHub"
              />
            </a>
            <a href="#linkedin" aria-label="LinkedIn">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9b5932427c769da5a1a54682d550e1e0d62c1e6440b05e6a1cd35aa32ac554f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                className="object-contain shrink-0 rounded aspect-[1.47] w-[47px]"
                alt="LinkedIn"
              />
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
