/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Logo from './Logo';
import NavLinks from './NavLinks';
import AuthButtons from './AuthButtons';

const Header: React.FC = () => {
  return (
    <header className="flex flex-col justify-center items-center px-16 py-2.5 w-full rounded-none bg-stone-950 shadow-[0px_1px_0px_rgba(71,70,70,0.25)] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between max-w-full w-[1376px]">
        <Logo />
        <NavLinks />
        <AuthButtons />
      </div>
    </header>
  );
};

export default Header;
