/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const HeroContent: React.FC = () => {
  return (
    <>
      <h1 className="mt-6 text-6xl tracking-tighter text-center leading-[62px] text-neutral-400 max-md:max-w-full max-md:text-4xl max-md:leading-[51px]">
        Finally, a Headless CMS <br />
        <span className="text-zinc-100">That Moves as Fast as You Do</span>
      </h1>
      <p className="mt-7 text-base tracking-tight leading-6 text-center text-neutral-400 max-md:max-w-full">
        BaseHub is the fastest and most flexible Headless CMS. Develop with
        end-to-end typesafety, write <br />
        with the help of AI, and collaborate in real time with your team.
      </p>
    </>
  );
};

export default HeroContent;
