/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import BlogIntro from './BlogIntro';
import HeroContent from './HeroContent';
import UsedBy from './UsedBy';

const Hero: React.FC = () => {
  return (
    <section className="flex flex-col items-center px-20 pt-20 pb-40 w-full bg-black max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <div className="flex flex-col items-center -mb-8 ml-14 w-full max-w-[1442px] max-md:mb-2.5 max-md:max-w-full">
        <BlogIntro />
        <HeroContent />
        <UsedBy />
      </div>
    </section>
  );
};

export default Hero;
