/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Logo: React.FC = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/0cb9fb5f066e452362c9745e8225cbf2dbd25bcade27529396f296d32a3c5621?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
      className="object-contain shrink-0 aspect-[3.29] w-[92px]"
      alt="BaseHub Logo"
    />
  );
};

export default Logo;
