/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Mission: React.FC = () => {
  return (
    <section className="self-start mt-44 max-md:mt-10">
      <h2 className="text-6xl font-light tracking-tighter leading-[67px] text-neutral-400 max-md:max-w-full max-md:text-4xl max-md:leading-[55px]">
        Our goal is to break through the <br />
        "developer vs marketer" dichotomy.
      </h2>
      <p className="mt-9 text-6xl font-light tracking-tighter leading-[67px] text-zinc-100 max-md:max-w-full max-md:text-4xl max-md:leading-[55px]">
        We work to <span className="text-orange-500">delight everyone</span>{' '}
        who's <br />
        working on content-driven websites.
      </p>
      <a
        href="#mission"
        className="flex overflow-hidden gap-2.5 self-start px-3.5 py-2.5 mt-9 text-sm font-medium tracking-tight leading-none text-center bg-zinc-900 rounded-[96px] text-stone-300"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c5fdeb48bfcb109a0142c622326c3ef1b7b02c9d1b493762426dbf40e433efbe?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
          className="object-contain shrink-0 aspect-square w-[15px]"
          alt=""
        />
        <span className="flex-auto my-auto">Read more about our mission</span>
      </a>
    </section>
  );
};

export default Mission;
