/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const NavLinks: React.FC = () => {
  return (
    <nav className="flex gap-3 items-start my-auto whitespace-nowrap">
      <a
        href="#pricing"
        className="grow self-stretch text-sm leading-loose text-neutral-400"
      >
        Pricing
      </a>
      <div className="flex gap-1.5 leading-loose">
        <a href="#templates" className="grow text-sm text-neutral-400">
          Templates
        </a>
        <span className="p-1 text-xs font-medium text-orange-500 rounded-full bg-orange-500 bg-opacity-20">
          New
        </span>
      </div>
      <div className="flex gap-5 text-sm text-neutral-400">
        <a href="#documentation" className="grow leading-loose">
          Documentation
        </a>
        <a href="#blog">Blog</a>
        <a href="#changelog" className="leading-loose">
          Changelog
        </a>
      </div>
    </nav>
  );
};

export default NavLinks;
