/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import PricingToggle from './PricingToggle';
import PricingPlans from './PricingPlans';
import FAQ from './FAQ';

const Pricing: React.FC = () => {
  return (
    <section className="mt-24 max-md:mt-10">
      <h2 className="text-3xl font-medium tracking-tighter leading-none text-center text-zinc-100">
        Pricing
      </h2>
      <p className="mt-5 text-lg tracking-tight leading-snug text-center text-neutral-400 max-md:max-w-full">
        Get started with a free Personal Account, or explore our paid options.
      </p>
      <PricingToggle />
      <PricingPlans />
      <FAQ />
    </section>
  );
};

export default Pricing;
