/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import PricingCard from './PricingCard';

const plans = [
  {
    name: 'Personal',
    price: 'Free',
    description:
      "Your personal workspace, ideal for hobby projects where you'll be mostly working on your own.",
    features: [
      '3k blocks across all your repos',
      'Bandwidth included',
      '75k API Requests',
      '25GB Asset Storage',
      '1M Asset Requests',
      'Search and Analytics, AI Chat',
      'Discord, community support',
    ],
    ctaText: 'Get started for Free',
    ctaSubtext: 'No credit card required',
  },
  {
    name: 'Team',
    price: '$15',
    priceSubtext: 'per user / billed monthly',
    description:
      'A team, perfect for startups and growing businesses that want to write great content for the web.',
    features: [
      'Unlimited blocks',
      'Real-time collaboration',
      '500k API Requests',
      '500GB Asset Storage',
      '5M Asset Requests',
      'Custom roles',
      'Priority support',
    ],
    ctaText: 'Get started',
    ctaSubtext: 'Payments secured by Stripe',
  },
  {
    name: 'Unlimited',
    price: '$350',
    priceSubtext: '/ billed monthly',
    description:
      'The unlimited experience, made for larger organizations needing to collaborate on lots of content.',
    features: [
      'Unlimited blocks, unlimited users',
      '5M API Requests (10x)',
      '5TB Asset Storage (20x)',
      '50M Asset Requests (10x)',
      'Dedicated support and onboarding',
    ],
    ctaText: 'Get started',
    ctaSubtext: 'Payments secured by Stripe',
  },
];

const PricingPlans: React.FC = () => {
  return (
    <div className="flex flex-col self-start mt-6 ml-24 max-w-full w-[1152px]">
      <div className="max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {plans.map((plan, index) => (
            <PricingCard key={index} {...plan} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default PricingPlans;
