/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface PricingCardProps {
  name: string;
  price: string;
  priceSubtext?: string;
  description: string;
  features: string[];
  ctaText: string;
  ctaSubtext: string;
}

const PricingCard: React.FC<PricingCardProps> = ({
  name,
  price,
  priceSubtext,
  description,
  features,
  ctaText,
  ctaSubtext,
}) => {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col items-start px-6 py-6 mx-auto w-full bg-black rounded-xl max-md:px-5 max-md:mt-6">
        <h3 className="text-base tracking-tight leading-loose text-zinc-100">
          {name}
        </h3>
        <div className="flex gap-2 mt-4">
          <span className="text-3xl tracking-tighter text-zinc-100">
            {price}
          </span>
          {priceSubtext && (
            <span className="flex-auto self-start mt-4 text-base tracking-tight leading-loose text-neutral-400">
              {priceSubtext}
            </span>
          )}
        </div>
        <p className="self-stretch mt-4 text-sm tracking-tight leading-5 text-zinc-100 max-md:mr-1.5">
          {description}
        </p>
        <h4 className="mt-12 text-xs font-medium tracking-tight leading-loose text-zinc-100 max-md:mt-10">
          {name === 'Personal' ? 'Includes:' : 'Everything in Personal, plus:'}
        </h4>
        <ul className="w-full mt-5">
          {features.map((feature, index) => (
            <li
              key={index}
              className="flex gap-1.5 mt-3.5 text-sm tracking-tight leading-loose text-neutral-400"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f12e5dfaeab2908cc32a31d580a9aca07d8fa36a33f6db124f5d0e5c2910702c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                className="object-contain shrink-0 w-4 aspect-square"
                alt=""
              />
              <span>{feature}</span>
            </li>
          ))}
        </ul>
        <div className="flex gap-5 justify-between self-stretch mt-12 max-md:mt-10">
          <button className="overflow-hidden px-3.5 py-2.5 text-sm font-medium tracking-tight leading-none text-center bg-zinc-900 rounded-[96px] text-stone-300">
            {ctaText}
          </button>
          <p className="my-auto text-sm tracking-tight leading-loose text-right text-stone-500">
            {ctaSubtext}
          </p>
        </div>
      </div>
    </div>
  );
};

export default PricingCard;
