/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Roadmap: React.FC = () => {
  return (
    <section className="self-stretch mt-56 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
          <div className="flex z-10 flex-col items-start mt-24 w-full text-sm tracking-tight max-md:mt-10 max-md:mr-0">
            <h2 className="text-3xl font-medium tracking-tighter leading-none text-zinc-100">
              Our Roadmap
            </h2>
            <p className="self-stretch mt-5 text-lg tracking-tight leading-7 text-neutral-400">
              See the milestones that brought us here, and get a sneak peak of
              what's next.
            </p>
            <p className="mt-8 leading-loose text-neutral-400">
              Have some feature request?
            </p>
            <p className="flex gap-px mt-2 leading-loose">
              <span className="grow text-zinc-100">Join our Discord</span>
              <span className="text-neutral-400"> and tell us more!</span>
            </p>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-9/12 max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5acadb4493e5c8bc458c13b8a9acd78c25649abba8e346f3ad3f201cf52292b7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
            className="object-contain grow w-full aspect-[1.9] max-md:max-w-full"
            alt="Roadmap visualization"
          />
        </div>
      </div>
    </section>
  );
};

export default Roadmap;
