/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import TestimonialCard from './TestimonialCard';

const testimonials = [
  {
    name: "Brotzky",
    handle: "@brotzky_",
    avatarSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/e581d6a36b7c0710fb870f4bc6fcffaf236d7daa34e1f2161f5ed5f6761c28e5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
    content: [
      "Just got access to @basehub_ai... !",
      "Even in alpha you know this is going to be special.",
      "We currently use Sanity and previously Contentful — but now I want to use Basehub."
    ]
  },
  {
    name: "Evan Stewart",
    handle: "@heyecs",
    avatarSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/c17d0ab2103454b3c06f176812e05bac2cf944ecd28b1d0e59881ec354216cb4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
    content: [
      "I can't get over how insanely easy it is to scaffold large stores of content with @basehub_ai My entire personal site (http://evanstewart.xyz) and a large bulk of @BasewellHQ's content (blog, media, changelog) is delivered w/Basehub.",
      "DX is top-notch… highly recommended!"
    ]
  },
  {
    name: "Guillermo Rauch",
    handle: "@rauchg",
    avatarSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/10faa6ccbd3778f5ebb330657868c15681a057a8d1a0da3258e98fa37c61ea14?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
    content: [
      "A document with an API.",
      "Content modeling and a Notion-like block editing experience in one."
    ]
  },
  {
    name: "Michelle Bakels",
    handle: "@MichelleBakels",
    avatarSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/c143460d2d3683699adaff8f6347059691d480efbfba14c3e2fea1976e80cfb0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
    content: [
      Continuing from where we left off:

      "The full @ReactMiamiConf speaker lineup was announced today!! 🎉",
      "All content was prepared and pushed to prod in one push with @basehub_ai.",
      "What was once a very stressful day went flawlessly."
    ]
  },
  {
    name: "Jayzers",
    handle: "@jayzersdotdev",
    avatarSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/7cde2ddb884ac689af6430987becc34baf1b5ec478b86b515479685ee18a6c0e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
    content: [
      "the quality of the ui, the amount of features that @basehub_ai delivers so fast is crazyyy"
    ]
  },
  {
    name: "Steven Tey",
    handle: "@steventey",
    avatarSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/0b0e2039cca78d3299e6a0e44c3ff76d74062cef193d23abc809a19939fb24dd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
    content: [
      "If you're looking for a CMS in 2024, @basehub_ai is a breathe of fresh air over archaic incumbents like Contentful:",
      "◆ AI-native experience (create blocks using natural language)",
      "◆ E2E typesafety (auto-generated types from your repo)",
      "◆ Optimistic UI (changes are auto-saved)"
    ]
  }
];

const Testimonials: React.FC = () => {
  return (
    <section className="flex flex-col items-center self-stretch pl-12 mt-11 w-full max-md:pl-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-center mt-48 text-3xl font-medium tracking-tighter leading-none text-center text-zinc-100 max-md:mt-10">What People Are Saying</h2>
      <p className="flex gap-1.5 self-center mt-5 tracking-tight text-center">
        <span className="grow text-lg leading-loose text-zinc-100">Follow us on X</span>
        <span className="flex-auto text-lg leading-loose text-neutral-500"> to join the conversation.</span>
      </p>
      <div className="self-start max-w-full w-[1236px]">
        <div className="flex gap-5 max-md:flex-col">
          {testimonials.map((testimonial, index) => (
            <TestimonialCard key={index} {...testimonial} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Testimonials;