/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface TestimonialCardProps {
  name: string;
  handle: string;
  avatarSrc: string;
  content: string[];
}

const TestimonialCard: React.FC<TestimonialCardProps> = ({
  name,
  handle,
  avatarSrc,
  content,
}) => {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow max-md:mt-6">
        <div className="flex flex-col px-6 py-7 w-full rounded-lg bg-neutral-900 max-md:px-5">
          <div className="flex gap-3 whitespace-nowrap">
            <img
              loading="lazy"
              src={avatarSrc}
              className="object-contain shrink-0 w-14 rounded-full aspect-square"
              alt={`${name}'s avatar`}
            />
            <div className="flex flex-col grow shrink-0 my-auto basis-0 w-fit">
              <div className="flex gap-5 justify-between text-base font-medium tracking-tight text-zinc-100">
                <div>{name}</div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/07252fddef4efb2159a60d61cfacfc3503a7a96022d12313f40b23400779ce82?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                  className="object-contain shrink-0 self-start w-4 aspect-square"
                  alt="Twitter logo"
                />
              </div>
              <div className="self-start mt-1.5 text-sm tracking-tight text-neutral-400">
                {handle}
              </div>
            </div>
          </div>
          {content.map((paragraph, index) => (
            <p
              key={index}
              className={`${
                index === 0 ? 'mt-7' : 'mt-6'
              } text-sm tracking-tight leading-loose text-stone-300`}
            >
              {paragraph}
            </p>
          ))}
        </div>
      </div>
    </div>
  );
};

export default TestimonialCard;
