/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const UsedBy: React.FC = () => {
  return (
    <>
      <p className="mt-8 text-xs tracking-tight leading-loose text-neutral-400">
        Used by
      </p>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a8f05610b1eb5ad364064655846771ed6cb84d5ff4d457603a742928f99b2a07?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
        className="object-contain self-start mt-2 max-w-full rounded-3xl aspect-[1.41] w-[1328px]"
        alt="Companies using BaseHub"
      />
    </>
  );
};

export default UsedBy;
