import { FILE } from "dns"
import { from } from "svix/dist/openapi/rxjsStub"

/**
 * This code was generated by Builder.io.
 */
Continuing from where we left off:

<FILE path="components/CodeBlock.tsx">
import React from 'react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { tomorrow } from 'react-syntax-highlighter/dist/esm/styles/prism';

interface CodeBlockProps {
  filename: string;
  code: string;
}

const CodeBlock: React.FC<CodeBlockProps> = ({ filename, code }) => {
  return (
    <div className="flex flex-col mt-10 w-full max-md:max-w-full">
      <div className="flex overflow-hidden flex-col py-px pr-px w-full rounded-md border border-solid border-zinc-800 max-md:max-w-full">
        <div className="flex flex-wrap items-center py-2 pr-3 pl-4 w-full bg-black rounded-md border-solid border-b-[0.8px] border-b-zinc-800 min-h-[48px] max-md:max-w-full">
          <div className="flex flex-col flex-1 shrink items-start self-stretch my-auto basis-0 min-w-[94px] pr-[620px] max-md:max-w-full">
            <div className="flex gap-2 items-center">
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/94f95bbff9bcb4f644acbb30b12f58c26edf0260f3c255a24ad20c9789cc6e9d?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197" alt="" className="object-contain self-stretch my-auto aspect-square w-[17px]" />
              <div className="overflow-hidden self-stretch py-px my-auto text-sm whitespace-nowrap text-neutral-400">{filename}</div>
            </div>
          </div>
          <div className="flex items-start self-stretch my-auto w-8">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e2aa8d414564cce28079554a104dfcb2fbacbd6e0b2e9a5c8091a757030b274?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197" alt="" className="object-contain w-8 rounded-md aspect-square" />
          </div>
        </div>
        <SyntaxHighlighter language="javascript" style={tomorrow} customStyle={{
          background: '#0a0a0a',
          padding: '20px',
          borderRadius: '0 0 6px 6px',
          margin: 0,
        }}>
          {code}
        </SyntaxHighlighter>
      </div>
    </div>
  );
};

export default CodeBlock;