/**
 * This code was generated by Builder.io.
 */

const CTASection: React.FC = () => {
  return (
    <section className="flex overflow-hidden flex-col items-center pr-14 pl-14 w-full bg-black max-md:px-5 max-md:max-w-full">
      <div className="flex relative justify-between py-32 pr-32 pl-6 max-w-full w-[1248px] max-md:px-5 max-md:py-24">
        <div className="flex absolute top-0 z-0 self-start h-px bg-[linear-gradient(90deg,#000_0%,#333_10%,#333_90%,#000_100%)] left-[-54px] min-h-[1px] w-[1440px] max-md:max-w-full" />
        <div className="flex z-0 flex-col min-w-[320px] w-[684px] max-md:max-w-full">
          <h2 className="flex flex-wrap items-center w-full text-5xl font-extrabold tracking-tighter whitespace-nowrap max-md:max-w-full max-md:text-4xl">
            <span className="bg-clip-text bg-[linear-gradient(90deg,#007CF0_0%,#00DFD8_100%)] text-transparent">
              Develop.
            </span>
            <span className="bg-clip-text bg-[linear-gradient(90deg,#7928CA_0%,#FF0080_100%)] text-transparent">
              Preview.
            </span>
            <span className="bg-clip-text bg-[linear-gradient(90deg,#FF4D4D_0%,#F9CB28_100%)] text-transparent">
              Ship.
            </span>
          </h2>
          <p className="mt-5 w-full text-lg tracking-normal leading-7 max-w-[684px] text-neutral-400 max-md:max-w-full">
            Vercel is the platform for frontend developers, providing the speed
            and reliability innovators need to create at the moment of
            inspiration.
          </p>
        </div>
        <div className="flex z-0 flex-col flex-1 shrink justify-center py-3 text-base font-medium basis-0 max-w-[200px]">
          <a
            href="#"
            className="flex justify-center items-center px-9 py-3 w-full leading-loose bg-gray-200 rounded-lg max-w-[200px] min-h-[48px] min-w-[140px] text-neutral-950 max-md:px-5"
          >
            Start Deploying
          </a>
          <a
            href="#"
            className="flex justify-center items-center px-8 py-3 mt-4 w-full leading-loose text-white bg-black rounded-lg shadow-sm max-w-[198px] min-h-[46px] min-w-[138px] max-md:px-5"
          >
            Tour the Product
          </a>
        </div>
        <div className="flex absolute inset-0 z-0 shrink-0 self-start bg-white bg-opacity-10 h-[375px] min-w-[240px] w-[1248px] max-md:max-w-full" />
      </div>
    </section>
  );
};

export default CTASection;
