/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col items-center pt-px pr-36 pb-24 pl-36 w-full border-solid bg-neutral-950 border-t-[0.8px] border-t-white border-t-opacity-10 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col justify-between w-full max-w-[1080px] max-md:max-w-full">
        <FooterLinks />
        <FooterBottom />
      </div>
    </footer>
  );
};

const FooterLinks: React.FC = () => {
  // Footer links data...
  const footerSections = [
    {
      title: "Products",
      links: [
        "AI",
        "Enterprise",
        "Next.js",
        "Observability",
        "Previews",
        "Rendering",
        "Security",
        "Turbo",
        "v0",
      ],
    },
    {
      title: "Resources",
      links: [
        "Community",
        "Docs",
        "Experts",
        "Guides",
        "Help",
        "Integrations",
        "Pricing",
        "Resources",
        "Templates",
      ],
    },
    {
      title: "Company",
      links: [
        "About",
        "Blog",
        "Careers",
        "Changelog",
        "Contact Us",
        "Customers",
        "Partners",
        "Legal",
      ],
    },
    {
      title: "Social",
      links: ["GitHub", "LinkedIn", "Twitter", "YouTube"],
    },
  ];

  return (
    <div className="flex flex-wrap gap-10 w-full max-md:max-w-full">
      {footerSections.map((section, index) => (
        <div key={index} className="flex flex-col w-3/12 max-md:w-full">
          <div className="flex flex-col grow pt-3 h-[330px]">
            <h3 className="py-px w-full text-sm font-medium text-gray-200 whitespace-nowrap">
              {section.title}
            </h3>
            <ul className="flex flex-col mt-3 w-full">
              {section.links.map((link, linkIndex) => (
                <li
                  key={linkIndex}
                  className="flex flex-col justify-center items-start py-1.5 w-full text-sm leading-none whitespace-nowrap text-zinc-500"
                >
                  <a href="#" className="hover:text-zinc-400">
                    {link}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      ))}
    </div>
  );
};

const FooterBottom: React.FC = () => {
  return (
    <div className="flex flex-col self-end pt-8 w-full max-w-[1088px] min-h-[66px] max-md:max-w-full">
      <div className="flex flex-wrap justify-between items-center w-full min-h-[34px] max-md:max-w-full">
        <div className="flex flex-col self-stretch my-auto text-sm leading-none text-blue-600 max-w-[1080px] w-[153px]">
          <div className="flex gap-1.5 items-center px-2 py-2 w-full rounded-md max-w-[300px] min-h-[34px]">
            <div className="flex shrink-0 self-stretch my-auto w-2 h-2 bg-blue-600 rounded-lg" />
            <div className="overflow-hidden self-stretch my-auto">
              All systems normal
            </div>
          </div>
        </div>
        <div className="flex flex-col flex-1 shrink items-end self-stretch my-auto basis-0 min-h-[24px] min-w-[72px] pl-[863px] max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9c4b6dde110dd8e2df0fbd0328249a6a8d7c517569711918e67b467067e1f230?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
            alt="Vercel Logo"
            className="object-contain shadow-sm aspect-[3] min-h-[24px] w-[72px]"
          />
        </div>
      </div>
    </div>
  );
};

export default Footer;
