/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";
import UserActions from "./UserActions";

const Header: React.FC = () => {
  return (
    <header className="flex justify-center items-center py-4 bg-black shadow-sm min-h-[64px]">
      <div className="flex flex-wrap items-center self-stretch pr-6 pl-5 my-auto min-h-[32px] w-[1355px] max-md:pr-5 max-md:max-w-full">
        <Logo />
        <Navigation />
        <UserActions />
      </div>
    </header>
  );
};

export default Header;
