/**
 * This code was generated by Builder.io.
 */
import Footer from "./Footer";
import Header from "./Header";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex relative flex-col bg-[linear-gradient(0deg,#000_0%,#000_100%,#000)] min-h-[5741px]">
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
