/**
 * This code was generated by Builder.io.
 */

const Logo: React.FC = () => {
  return (
    <div className="flex items-center self-stretch my-auto w-[105px]">
      <div className="flex items-start self-stretch p-1 my-auto rounded-md w-[105px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2cfff32c1e447a9d5ad7be788de27faf55aa6a93732e338caa0119feed82e60d?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
          alt="Company Logo"
          className="object-contain aspect-[4.41] w-[97px]"
        />
      </div>
    </div>
  );
};

export default Logo;
