/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NavItem {
  label: string;
  href: string;
}

const navItems: NavItem[] = [
  { label: "Products", href: "#" },
  { label: "Solutions", href: "#" },
  { label: "Resources", href: "#" },
  { label: "Enterprise", href: "#" },
  { label: "Docs", href: "#" },
  { label: "Pricing", href: "#" },
];

const Navigation: React.FC = () => {
  return (
    <nav className="flex flex-col self-stretch pl-8 my-auto text-sm leading-none whitespace-nowrap min-w-[240px] text-neutral-400 w-[561px] max-md:max-w-full">
      <ul className="flex justify-center items-center w-full max-md:max-w-full">
        <li className="flex flex-col self-stretch my-auto min-w-[240px] w-[531px] max-md:max-w-full">
          <ul className="flex flex-wrap justify-center w-full max-md:max-w-full">
            {navItems.map((item, index) => (
              <li
                key={index}
                className="flex grow shrink justify-center items-center h-full text-center"
              >
                <a
                  href={item.href}
                  className="flex gap-1.5 self-stretch px-3.5 py-2 my-auto rounded-full"
                >
                  {item.label}
                  {index < 3 && (
                    <img
                      loading="lazy"
                      src={`http://b.io/ext_${index + 2}-`}
                      alt=""
                      className="object-contain shrink-0 w-3.5 aspect-square"
                    />
                  )}
                </a>
              </li>
            ))}
          </ul>
        </li>
      </ul>
    </nav>
  );
};

export default Navigation;
