/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface Author {
  name: string;
  role: string;
  avatar: string;
}

const authors: Author[] = [
  {
    name: "Javi Velasco",
    role: "Software Engineer, Infrastructure",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5b3ebace2caa5536930095bd5ecea20440c5560b77266034cd97c403c1b9ed19?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
  },
  {
    name: "Mariano Cocirio",
    role: "Product Manager",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1f718c7531376a59995af3b9419d4d70eaf7f1876aa883bb2423642fb72ddee0?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
  },
  {
    name: "Tom Lienard",
    role: "Software Engineer, Infrastructure",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/465d8325a13824246dab04918c9c9dabfb0fa25c3467e4bf48558c8f83c1f989?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
  },
  {
    name: "Craig Andrews",
    role: "Software Engineer, Infrastructure",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9309de4a8f8799741c68a12912ecdb00f533e8f1fdea535bdcbb2bb6717543f8?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
  },
  {
    name: "Doug Parsons",
    role: "Software Engineer",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a344f0369c59ade5218a3049157cf58341fb378d9f86be50ddbcd7513b0da80a?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197",
  },
];

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col grow shrink px-10 text-sm min-w-[240px] w-[272px] max-md:px-5">
      <div className="flex flex-col w-full">
        <div className="w-full leading-none text-neutral-400">Posted by</div>
        {authors.map((author, index) => (
          <div
            key={index}
            className="flex gap-3 items-center py-px mt-4 w-full tracking-normal min-h-[40px]"
          >
            <img
              loading="lazy"
              src={author.avatar}
              alt={`${author.name}'s avatar`}
              className="object-contain shrink-0 self-stretch my-auto w-9 aspect-square"
            />
            <div className="flex flex-col self-stretch my-auto w-[210px]">
              <div className="flex flex-col pr-1 w-full font-semibold leading-none text-gray-200">
                <div className="w-full">{author.name}</div>
              </div>
              <div className="w-full leading-none min-h-[16px] text-neutral-400">
                {author.role}
              </div>
            </div>
          </div>
        ))}
      </div>
    </aside>
  );
};

export default Sidebar;
