/**
 * This code was generated by Builder.io.
 */

const UserActions: React.FC = () => {
  return (
    <div className="flex flex-1 shrink justify-center items-center self-stretch pl-96 my-auto basis-0 min-w-[240px] max-md:max-w-full">
      <div className="flex flex-col self-stretch my-auto min-w-[240px] w-[242px]">
        <div className="flex items-center w-full">
          <div className="flex flex-col self-stretch px-3 my-auto text-sm font-medium whitespace-nowrap">
            <div className="flex gap-3 items-center">
              <button className="flex overflow-hidden justify-center items-center self-stretch p-1.5 my-auto leading-none text-gray-200 rounded-md shadow-sm bg-neutral-950 max-w-[185px] min-h-[32px]">
                <span className="overflow-hidden self-stretch px-1.5 my-auto">
                  Contact
                </span>
              </button>
              <button className="flex overflow-hidden justify-center items-center self-stretch p-1.5 my-auto leading-none rounded-md shadow-sm bg-neutral-950 max-w-[185px] min-h-[32px] text-neutral-400">
                <span className="overflow-hidden self-stretch px-1.5 my-auto">
                  Dashboard
                </span>
              </button>
            </div>
          </div>
          <div className="flex flex-col self-stretch my-auto w-8">
            <div className="flex flex-col w-full max-w-[32px] rounded-[32px]">
              <div className="flex overflow-hidden justify-center items-center w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/0426986dbb5ce6784ddd947695db4486ab71830ee628a0e9df258ff7698bf331?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                  alt="User avatar"
                  className="object-contain flex-1 shrink self-stretch my-auto w-full aspect-square basis-0"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default UserActions;
