import Providers from '@/core/lib/providers';
import { SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/nextjs';
import '@styles/app.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: PageProps) {
    return (
        <Providers>
            <html lang="en">
                <body className={inter.className}>
                    {children}
                    <SignedOut>
                        <SignInButton />
                    </SignedOut>
                    <SignedIn>
                        <UserButton />
                    </SignedIn>
                </body>
            </html>
        </Providers>
    );
}