/**
 * This code was generated by Builder.io.
 */
import Sidebar from "../../../../../a/ExploreComponents/Sidebar";
import VerticalNavbar from "../../../../../a/ExploreComponents/VerticalNavbar";

const ExploreLayout: React.FC = () => (
  <div className="flex flex-wrap min-h-[878px]">
    <VerticalNavbar />
    <Sidebar />
  </div>
);

export default ExploreLayout;
