/**
 * This code was generated by Builder.io.
 */
import BlogContent from "./components/BlogContent";
import BlogHeader from "./components/BlogHeader";
import CTASection from "./components/CTASection";
import Layout from "./components/Layout";
import Sidebar from "./components/Sidebar";

const BlogPost: React.FC = () => {
  return (
    <Layout>
      <BlogHeader
        category="Engineering"
        date="Thursday, July 4th 2024"
        title="Function streaming to be framework-agnostic on Vercel"
        subtitle="Streaming will soon be enabled by default for all Node.js Vercel Functions"
      />
      <div className="flex flex-wrap justify-center self-center px-6 max-w-full min-h-[4421px] w-[1248px] max-md:px-5">
        <BlogContent />
        <Sidebar />
      </div>
      <CTASection />
    </Layout>
  );
};

export default BlogPost;
