/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Layout from '../components/Layout';
import Hero from '../components/Hero';
import FeatureSection from '../components/FeatureSection';
import AdditionalFeatures from '../components/AdditionalFeatures';
import CTABanner from '../components/CTABanner';
import Mission from '../components/Mission';
import Testimonials from '../components/Testimonials';
import Roadmap from '../components/Roadmap';
import Pricing from '../components/Pricing';
import CTASection from '../components/CTASection';

const Home: React.FC = () => {
  return (
    <Layout>
      <Hero />
      <FeatureSection />
      <AdditionalFeatures />
      <CTABanner />
      <Mission />
      <Testimonials />
      <Roadmap />
      <Pricing />
      <CTASection />
    </Layout>
  );
};

export default Home;
